/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using CredofasterPartnerApi.Standard.Controllers;
using CredofasterPartnerApi.Standard.Http.Client;
using CredofasterPartnerApi.Standard.Utilities;

namespace CredofasterPartnerApi.Standard
{
    public partial class CredofasterPartnerApiClient
    {

        /// <summary>
        /// Singleton access to Main controller
        /// </summary>
        public MainController Main
        {
            get
            {
                return MainController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Events controller
        /// </summary>
        public EventsController Events
        {
            get
            {
                return EventsController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public CredofasterPartnerApiClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public CredofasterPartnerApiClient(string apiKey = "XXXX-XXXX-XXXX-XXXX", string clientId = "ABCDEDFG1234")
        {
            Configuration.ApiKey = apiKey;
            Configuration.ClientId = clientId;
        }
        #endregion
    }
}