/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class Denomination : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name = "KE";
        private int mvalue = 10;

        /// <summary>
        /// Available Name: KE
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Amount to Request
        /// </summary>
        [JsonProperty("value")]
        public int Value 
        { 
            get 
            {
                return this.mvalue; 
            } 
            set 
            {
                this.mvalue = value;
                onPropertyChanged("Value");
            }
        }
    }
} 