/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class EventCallbackPayload : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string eventId = "123456789";
        private string eventType = "QUEUED";
        private string requestId;
        private object eventData;

        /// <summary>
        /// This is shared by the system and should be referred when doing any debugging
        /// </summary>
        [JsonProperty("EventId")]
        public string EventId 
        { 
            get 
            {
                return this.eventId; 
            } 
            set 
            {
                this.eventId = value;
                onPropertyChanged("EventId");
            }
        }

        /// <summary>
        /// Contains the EVENT type.  detailed list of this can be shared on Request to the admin
        /// </summary>
        [JsonProperty("EventType")]
        public string EventType 
        { 
            get 
            {
                return this.eventType; 
            } 
            set 
            {
                this.eventType = value;
                onPropertyChanged("EventType");
            }
        }

        /// <summary>
        /// For Events that are related with the Clients Request, you will get a Request ID that was generate by the system when you made a  service call
        /// </summary>
        [JsonProperty("RequestId")]
        public string RequestId 
        { 
            get 
            {
                return this.requestId; 
            } 
            set 
            {
                this.requestId = value;
                onPropertyChanged("RequestId");
            }
        }

        /// <summary>
        /// Contains any addition fields,(CAN BE NESTED). See the PDF for more details
        /// </summary>
        [JsonProperty("EventData")]
        public object EventData 
        { 
            get 
            {
                return this.eventData; 
            } 
            set 
            {
                this.eventData = value;
                onPropertyChanged("EventData");
            }
        }
    }
} 