/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class PartnerAirtimeResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int errorCode = 0;
        private string errorDescription;
        private Guid referenceId;
        private Guid requestId;

        /// <summary>
        /// Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
        /// </summary>
        [JsonProperty("ErrorCode")]
        public int ErrorCode 
        { 
            get 
            {
                return this.errorCode; 
            } 
            set 
            {
                this.errorCode = value;
                onPropertyChanged("ErrorCode");
            }
        }

        /// <summary>
        /// Text Description
        /// </summary>
        [JsonProperty("ErrorDescription")]
        public string ErrorDescription 
        { 
            get 
            {
                return this.errorDescription; 
            } 
            set 
            {
                this.errorDescription = value;
                onPropertyChanged("ErrorDescription");
            }
        }

        /// <summary>
        /// a UUID Returned for the Transaction
        /// </summary>
        [JsonProperty("ReferenceId")]
        public Guid ReferenceId 
        { 
            get 
            {
                return this.referenceId; 
            } 
            set 
            {
                this.referenceId = value;
                onPropertyChanged("ReferenceId");
            }
        }

        /// <summary>
        /// Return of the Clients Request ID
        /// </summary>
        [JsonProperty("RequestId")]
        public Guid RequestId 
        { 
            get 
            {
                return this.requestId; 
            } 
            set 
            {
                this.requestId = value;
                onPropertyChanged("RequestId");
            }
        }
    }
} 