/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class PartnerAirtimeBalanceResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int errorCode = 0;
        private string errorDescription = "Success.";
        private long unitBalance = 0L;
        private long limit = 0L;

        /// <summary>
        /// Code for the Request API Generated. 0: Success, Any other Error Code, refer to ErrorCodes Page
        /// </summary>
        [JsonProperty("ErrorCode")]
        public int ErrorCode 
        { 
            get 
            {
                return this.errorCode; 
            } 
            set 
            {
                this.errorCode = value;
                onPropertyChanged("ErrorCode");
            }
        }

        /// <summary>
        /// Text Description
        /// </summary>
        [JsonProperty("ErrorDescription")]
        public string ErrorDescription 
        { 
            get 
            {
                return this.errorDescription; 
            } 
            set 
            {
                this.errorDescription = value;
                onPropertyChanged("ErrorDescription");
            }
        }

        /// <summary>
        /// Remaining Tentative Balance
        /// </summary>
        [JsonProperty("UnitBalance")]
        public long UnitBalance 
        { 
            get 
            {
                return this.unitBalance; 
            } 
            set 
            {
                this.unitBalance = value;
                onPropertyChanged("UnitBalance");
            }
        }

        /// <summary>
        /// Limit of Units to Use.
        /// </summary>
        [JsonProperty("Limit")]
        public long Limit 
        { 
            get 
            {
                return this.limit; 
            } 
            set 
            {
                this.limit = value;
                onPropertyChanged("Limit");
            }
        }
    }
} 