/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class PartnerAirtimeRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Initiator initiator;
        private List<Models.SingleAirtimeParameter> parameters;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("initiator")]
        public Models.Initiator Initiator 
        { 
            get 
            {
                return this.initiator; 
            } 
            set 
            {
                this.initiator = value;
                onPropertyChanged("Initiator");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("parameters")]
        public List<Models.SingleAirtimeParameter> Parameters 
        { 
            get 
            {
                return this.parameters; 
            } 
            set 
            {
                this.parameters = value;
                onPropertyChanged("Parameters");
            }
        }
    }
} 