/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class RegisterCallbackRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string url = "https://posthere.io/partner_test";
        private string tps = "10";
        private string retries = "1,5";

        /// <summary>
        /// Define a reachable URL that accepts a JSON Payload as described below
        /// </summary>
        [JsonProperty("url")]
        public string Url 
        { 
            get 
            {
                return this.url; 
            } 
            set 
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }

        /// <summary>
        /// Define the transactions per second we should use when pushing callbacks to your side
        /// </summary>
        [JsonProperty("tps")]
        public string Tps 
        { 
            get 
            {
                return this.tps; 
            } 
            set 
            {
                this.tps = value;
                onPropertyChanged("Tps");
            }
        }

        /// <summary>
        /// A comma separated value, containing the number of seconds to wait for any retries and the max number of retries to do, when the clients endpoint responds with an Error
        /// </summary>
        [JsonProperty("retries")]
        public string Retries 
        { 
            get 
            {
                return this.retries; 
            } 
            set 
            {
                this.retries = value;
                onPropertyChanged("Retries");
            }
        }
    }
} 