/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class RegisterCallbackResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int errorCode;
        private string errorDescription;
        private string registeredCallbackUrl;
        private Guid requestId;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ErrorCode")]
        public int ErrorCode 
        { 
            get 
            {
                return this.errorCode; 
            } 
            set 
            {
                this.errorCode = value;
                onPropertyChanged("ErrorCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ErrorDescription")]
        public string ErrorDescription 
        { 
            get 
            {
                return this.errorDescription; 
            } 
            set 
            {
                this.errorDescription = value;
                onPropertyChanged("ErrorDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RegisteredCallbackUrl")]
        public string RegisteredCallbackUrl 
        { 
            get 
            {
                return this.registeredCallbackUrl; 
            } 
            set 
            {
                this.registeredCallbackUrl = value;
                onPropertyChanged("RegisteredCallbackUrl");
            }
        }

        /// <summary>
        /// Tracking RequestId
        /// </summary>
        [JsonProperty("RequestId")]
        public Guid RequestId 
        { 
            get 
            {
                return this.requestId; 
            } 
            set 
            {
                this.requestId = value;
                onPropertyChanged("RequestId");
            }
        }
    }
} 