/*
 * CredofasterPartnerApi.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using CredofasterPartnerApi.Standard;
using CredofasterPartnerApi.Standard.Utilities;


namespace CredofasterPartnerApi.Standard.Models
{
    public class SingleAirtimeParameter : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Guid referenceId;
        private string country = "KE";
        private string accountNo = "254705126329";
        private Models.Denomination denomination;
        private object other;

        /// <summary>
        /// A UUID for Each
        /// </summary>
        [JsonProperty("reference_id")]
        public Guid ReferenceId 
        { 
            get 
            {
                return this.referenceId; 
            } 
            set 
            {
                this.referenceId = value;
                onPropertyChanged("ReferenceId");
            }
        }

        /// <summary>
        /// Which Country are you requesting in
        /// </summary>
        [JsonProperty("country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// The Receipient's Account. Can be Phone Number(International Format)
        /// </summary>
        [JsonProperty("account_no")]
        public string AccountNo 
        { 
            get 
            {
                return this.accountNo; 
            } 
            set 
            {
                this.accountNo = value;
                onPropertyChanged("AccountNo");
            }
        }

        /// <summary>
        /// Currency Declarative Type
        /// </summary>
        [JsonProperty("denomination")]
        public Models.Denomination Denomination 
        { 
            get 
            {
                return this.denomination; 
            } 
            set 
            {
                this.denomination = value;
                onPropertyChanged("Denomination");
            }
        }

        /// <summary>
        /// Any Other Tags to accompany the Request
        /// </summary>
        [JsonProperty("other")]
        public object Other 
        { 
            get 
            {
                return this.other; 
            } 
            set 
            {
                this.other = value;
                onPropertyChanged("Other");
            }
        }
    }
} 